version: '3.6'
services:
  percona:
    container_name: db_percona
    image: percona
    environment:
      - MYSQL_DATABASE=isolations_locks
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./percona:/var/lib/mysql
    ports:
      - '3306:3306'

  postgres:
    container_name: db_postgres
    image: postgres
    environment:
      - POSTGRES_DB=isolations_locks
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'